"""Add last_enriched_at back to vacancies

Revision ID: 0d771352f047
Revises: 1f3d8d713256
Create Date: 2026-03-23 13:06:21.657086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d771352f047'
down_revision: Union[str, Sequence[str], None] = '1f3d8d713256'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('last_enriched_at', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacancies', 'last_enriched_at')
    # ### end Alembic commands ###
