"""your message here

Revision ID: 19590d632fb0
Revises: 95cb059bb264
Create Date: 2026-03-14 13:59:33.009489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19590d632fb0'
down_revision: Union[str, Sequence[str], None] = '95cb059bb264'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('last_successful_parse_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'last_successful_parse_date')
    # ### end Alembic commands ###
