"""Update vacancy model

Revision ID: 48135cf46a00
Revises: c1819df4569a
Create Date: 2026-03-12 12:51:22.097091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48135cf46a00'
down_revision: Union[str, Sequence[str], None] = 'c1819df4569a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('external_id', sa.String(length=50), nullable=False))
    op.add_column('vacancies', sa.Column('experience', sa.String(length=50), nullable=True))
    op.add_column('vacancies', sa.Column('employment', sa.String(length=50), nullable=True))
    op.add_column('vacancies', sa.Column('schedule', sa.String(length=50), nullable=True))
    op.add_column('vacancies', sa.Column('created_at_source', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'vacancies', ['external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vacancies', type_='unique')
    op.drop_column('vacancies', 'created_at_source')
    op.drop_column('vacancies', 'schedule')
    op.drop_column('vacancies', 'employment')
    op.drop_column('vacancies', 'experience')
    op.drop_column('vacancies', 'external_id')
    # ### end Alembic commands ###
