"""add error_message attempts timestamps to source_parse_tasks

Revision ID: 69b4fa245a8e
Revises: 70457ed0acb2
Create Date: 2026-03-16 17:44:08.589990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69b4fa245a8e'
down_revision: Union[str, Sequence[str], None] = '70457ed0acb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source_parse_tasks', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('source_parse_tasks', sa.Column('attempts', sa.Integer(), nullable=False))
    op.add_column('source_parse_tasks', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('source_parse_tasks', sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('source_parse_tasks', 'last_error')
    op.drop_column('sources', 'last_successful_parse_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('last_successful_parse_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('source_parse_tasks', sa.Column('last_error', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('source_parse_tasks', 'finished_at')
    op.drop_column('source_parse_tasks', 'started_at')
    op.drop_column('source_parse_tasks', 'attempts')
    op.drop_column('source_parse_tasks', 'error_message')
    # ### end Alembic commands ###
