"""add_profile_preferences

Revision ID: 72d7074051bd
Revises: ef74582c62a8
Create Date: 2026-04-21 15:03:46.384757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72d7074051bd'
down_revision: Union[str, Sequence[str], None] = 'ef74582c62a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('city_id', sa.Integer(), nullable=True))
    op.add_column('user_profiles', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('user_profiles', sa.Column('preferred_remote', sa.Boolean(), nullable=True))
    op.add_column('user_profiles', sa.Column('preferred_internship', sa.Boolean(), nullable=True))
    op.add_column('user_profiles', sa.Column('preferred_employment', sa.String(length=150), nullable=True))
    op.add_column('user_profiles', sa.Column('preferred_schedule', sa.String(length=150), nullable=True))
    op.add_column('user_profiles', sa.Column('bio', sa.String(length=1000), nullable=True))
    op.drop_constraint(op.f('user_profiles_desired_salary_currency_id_fkey'), 'user_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'user_profiles', 'cities', ['city_id'], ['id'], ondelete='SET NULL')
    op.drop_column('user_profiles', 'desired_salary_currency_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('desired_salary_currency_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_profiles', type_='foreignkey')
    op.create_foreign_key(op.f('user_profiles_desired_salary_currency_id_fkey'), 'user_profiles', 'currencies', ['desired_salary_currency_id'], ['id'])
    op.drop_column('user_profiles', 'bio')
    op.drop_column('user_profiles', 'preferred_schedule')
    op.drop_column('user_profiles', 'preferred_employment')
    op.drop_column('user_profiles', 'preferred_internship')
    op.drop_column('user_profiles', 'preferred_remote')
    op.drop_column('user_profiles', 'address')
    op.drop_column('user_profiles', 'city_id')
    # ### end Alembic commands ###
