"""Update models

Revision ID: 8a3a28227549
Revises: 48135cf46a00
Create Date: 2026-03-12 23:02:15.702603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a3a28227549'
down_revision: Union[str, Sequence[str], None] = '48135cf46a00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('cities_country_id_fkey'), 'cities', type_='foreignkey')
    op.drop_column('cities', 'country_id')
    op.add_column('vacancies', sa.Column('last_seen_at', sa.DateTime(), nullable=True))
    op.add_column('vacancies', sa.Column('fingerprint', sa.String(length=64), nullable=False))
    op.create_index(op.f('ix_vacancies_fingerprint'), 'vacancies', ['fingerprint'], unique=False)
    op.create_unique_constraint(None, 'vacancies', ['source_id', 'external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vacancies', type_='unique')
    op.drop_index(op.f('ix_vacancies_fingerprint'), table_name='vacancies')
    op.drop_column('vacancies', 'fingerprint')
    op.drop_column('vacancies', 'last_seen_at')
    op.add_column('cities', sa.Column('country_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('cities_country_id_fkey'), 'cities', 'countries', ['country_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
