"""remove_country_model

Revision ID: 8d1d1cecb2da
Revises: f5810e5be6b1
Create Date: 2026-03-31 12:12:54.622507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8d1d1cecb2da'
down_revision: Union[str, Sequence[str], None] = 'f5810e5be6b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'cities', ['name'])
    op.drop_column('cities', 'country_id')
    op.alter_column('vacancies', 'last_seen_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('vacancies', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vacancies', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('vacancies', 'last_seen_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.add_column('cities', sa.Column('country_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'cities', type_='unique')
    # ### end Alembic commands ###
