"""Update City model

Revision ID: c66ee8ccb8d1
Revises: 8a3a28227549
Create Date: 2026-03-12 23:05:01.555292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c66ee8ccb8d1'
down_revision: Union[str, Sequence[str], None] = '8a3a28227549'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('country_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cities', 'countries', ['country_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cities', type_='foreignkey')
    op.drop_column('cities', 'country_id')
    # ### end Alembic commands ###
