"""add_education_to_vacancy

Revision ID: ee81181d8e72
Revises: 1f2930f79ada
Create Date: 2026-03-27 13:03:18.666079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee81181d8e72'
down_revision: Union[str, Sequence[str], None] = '1f2930f79ada'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('education', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacancies', 'education')
    # ### end Alembic commands ###
