services:
  db:
    image: postgres:16
    container_name: vacancy_db
    env_file:
      - backend/.env.docker
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      retries: 5
      start_period: 5s
    networks:
      - vacancy-network

  redis:
    image: redis:8
    container_name: vacancy_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 5
      start_period: 5s
    networks:
      - vacancy-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: vacancy_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672" 
    env_file:
      - backend/.env.docker
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      retries: 5
      start_period: 10s
    networks:
      - vacancy-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: vacancy_backend
    env_file:
      - ./backend/.env.docker
    ports:
      - "8000:8000"
    volumes:
      - ./backend/vacancy_parser.session:/app/vacancy_parser.session
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - vacancy-network

  celery_worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: vacancy_celery_worker
    env_file:
      - ./backend/.env.docker
    command: ["celery", "-A", "src.core.celery.celery_app", "worker", "--loglevel=info"]
    volumes:
      - ./backend/vacancy_parser.session:/app/vacancy_parser.session
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - vacancy-network

  celery_beat:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: vacancy_celery_beat
    env_file:
      - ./backend/.env.docker
    command: ["celery", "-A", "src.core.celery.celery_app", "beat", "--loglevel=info"]
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - vacancy-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vacancy_frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env.docker
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - vacancy-network
  
  nginx:
    image: nginx:alpine
    container_name: vacancy_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    restart: unless-stopped
    networks:
      - vacancy-network


volumes:
  db_data:
  redis_data:
  rabbitmq_data:

networks:
  vacancy-network:
    driver: bridge
