[mypy]
python_version = 3.12
ignore_missing_imports = True
explicit_package_bases = True
disallow_untyped_defs = True
check_untyped_defs = true
disable_error_code = misc

exclude = 
    ^migrations/
    ^__pycache__/
    \.git/
    \.pytest_cache/
    \.mypy_cache/
    ^node_modules/
    ^build/
    ^lib/
    \.idea/
    \.vscode/
    \.ruff_cache/

[tool.mypy]
plugins = ["sqlalchemy.ext.mypy.plugin"]
