"""Fix bugs

Revision ID: 73f561326aed
Revises: 515237e7a20d
Create Date: 2025-11-27 23:37:30.239667

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "73f561326aed"
down_revision: Union[str, Sequence[str], None] = "515237e7a20d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_profiles", sa.Column("desired_salary", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_profiles", "desired_salary")
    # ### end Alembic commands ###
