"""Fix bugs

Revision ID: b5f3cce28427
Revises: 73f561326aed
Create Date: 2025-11-28 16:12:37.886206

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b5f3cce28427"
down_revision: Union[str, Sequence[str], None] = "73f561326aed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("comparison_vacancies", "id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "comparison_vacancies", sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False)
    )
    # ### end Alembic commands ###
